"""
Decoding Constants
==================

Shared literal types and constants for the decoding module. This module
centralizes the taxonomy used for models, metrics, and experimental
configurations to ensure scientific consistency and runtime safety.
"""

from typing import Literal

# --- Cross-Module Constants ---

GROUP_CV_STRATEGIES = {
    "group_kfold",
    "stratified_group_kfold",
    "leave_p_out",
    "leave_one_group_out",
    "group_shuffle_split",
}
"""Set of scikit-learn CV strategies that require a 'groups' array."""

CLASSICAL_FAMILIES = {
    "linear",
    "tree",
    "ensemble",
    "svm",
    "neighbors",
    "bayes",
    "dummy",
}
"""Architectural families that follow standard scikit-learn API patterns.
(e.g., scaling, feature selection).
"""

RESULT_SCHEMA_VERSION = "decoding_result_v1"
"""Version identifier for the serialized ExperimentResult payload."""

# --- Common Literal Types ---

MetricTask = Literal["classification", "regression"]
"""Type of predictive task being performed."""

ResponseMethod = Literal["predict", "proba", "score", "proba_or_score"]
"""The required estimator method to produce predictions for a metric."""

PredictionInterface = Literal["predict", "predict_proba", "decision_function"]
"""The actual scikit-learn API method names used for prediction."""

InputRank = Literal["2d", "3d_temporal", "tokens"]
"""The dimensionality/rank of the input data X."""

InputKind = Literal[
    "tabular",
    "temporal",
    "epoched",
    "embeddings",
    "tokens",
    "tabular_2d",
    "embedding_2d",
    "temporal_3d",
]
"""Semantic classification of the input data structure."""

EstimatorFamily = Literal[
    "linear",
    "tree",
    "ensemble",
    "svm",
    "neighbors",
    "neural",
    "bayes",
    "dummy",
    "temporal",
    "foundation",
]
"""High-level architectural family of the estimator."""

GroupedMetadata = Literal["none", "search_cv", "sfs_metadata_routing"]
"""Types of metadata generated by meta-estimators (e.g., GridSearch)."""

FeatureSelectionSupport = Literal["univariate", "sfs", "disabled"]
"""Level of feature selection supported or enabled."""

CalibrationSupport = Literal["eligible", "already_probabilistic", "unsupported"]
"""Whether an estimator supports post-hoc probability calibration."""

ImportanceSupport = Literal[
    "coefficients",
    "feature_importances",
    "permutation",
    "saliency",
    "unavailable",
]
"""The mechanism used to extract feature importance or weights."""

TemporalSupport = Literal["none", "sliding", "generalizing", "native"]
"""The level of temporal decoding logic supported by the model."""

DependencyGroup = Literal[
    "core",
    "mne",
    "torch",
    "braindecode",
    "transformers",
    "peft",
    "quant",
]
"""Optional dependency groups for lazy-loading and capability checking."""

MetricFamily = Literal[
    "label",
    "score_probability",
    "threshold_sweep",
    "calibration",
    "confusion",
    "regression",
]
"""Categorization of metrics for reporting and diagnostic grouping."""
